feat: added docker-compose for running postgres
EddieHubCommunity/CreatorsRegistry pull request #39
Opened 2024-06-18 03:55 UTC by sital002

## Fixes Issue
closes #35 

## Changes proposed
Added a docker compose file for running postgres database .

## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Screenshots

## Note to reviewers

2024-06-18 10:03 UTC, eddiejaoude requested changes
Thank you 👍 

Please can you add some docs to the README, on how to use this during development

2024-06-19 05:05 UTC, sital002 commented
> Please can you add some docs to the README, on how to use this during development

I have updated the documentation

2024-06-19 08:59 UTC, eddiejaoude commented on README.md
> +
```suggestion
### Postgres using Docker Compose

Note: you must have docker installed 

Run the docker command `docker-compose up -d`

```

2024-06-19 13:53 UTC, Pradumnasaraf requested changes
Hey,

Thanks for your contribution! This command was used in Compose V1, which is deprecated. Also, with the new version, the file naming convention has been updated.

For reference, please check out these links:
- [Docker Compose Up Command](https://docs.docker.com/reference/cli/docker/compose/up)
- [Docker Compose File](https://docs.docker.com/compose/compose-application-model)

Let me know if you have issues.

Comments: **Hold merge**

2024-06-19 13:53 UTC, Pradumnasaraf commented on README.md
> +Run the docker command `docker-compose up -d`
```suggestion
Run the docker command `docker compose up -d`
```

2024-06-19 13:53 UTC, Pradumnasaraf commented on docker-compose.yaml
Change file name to `compose.yaml` from `docker-compose.yaml`

2024-06-20 09:09 UTC, Pradumnasaraf approved these changes
Thank you for the changes. Looks good to merge!

2024-06-20 09:09 UTC, merged

2024-06-20 10:52 UTC, eddiejaoude commented
Thank you both! Great collab 💪